import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { getUser } from "@/app/lib/auth"
import { AuthProvider } from "@/app/context/AuthContext"
import { Providers } from "./providers"

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const user = await getUser()
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <AuthProvider initialUser={user}>
          <Providers>{children}</Providers>
        </AuthProvider>
      </body>
    </html>
  )
}
